app/main/routes.py
from flask import Blueprint, render_template
from flask_login import current_user
from app.models import Posts
from app import Config
from datetime import datetime
from hashids import Hashids

hashids = Hashids(min_length=5, salt=Config.SECRET_KEY)

main = Blueprint('main', __name__)

@main.route('/')
def home():

    posts = Posts.query.order_by(Posts.id.desc()).all()

    # not optimal. Should filter in the database query
    posts_for_display = []
    for p in posts:
        today = datetime.today().strftime('%Y-%m-%d')
        p_date = p.date_posted.strftime('%Y-%m-%d')
        p.date_str = p_date
        days_since = (datetime.strptime(today, '%Y-%m-%d') -\
             datetime.strptime(p_date, '%Y-%m-%d')).days
        if days_since == 0:
            p.days_since_post = 'Today'
        elif days_since == 1:
            p.days_since_post = f'{days_since} day ago'
        else:
            p.days_since_post = f'{days_since} days ago'

        # not optimal. Should filter in the database query
        if days_since <= 30 and p.paid:
            # pass the hashid so that jinja has it to send it back to backend upon click on job
            p.hashed_post_id = hashids.encode(p.id)
            posts_for_display.append(p)

    # make it so you cannot view home page if logged in
    # so that you don't forget to logout
    if current_user.is_authenticated:
        return render_template('logged_in.html', posts=posts_for_display)

    # reverse so that the newest posts are shown at the top of the list
    return render_template('home.html', posts=posts_for_display)

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/tos')
def tos():
    return render_template('tos.html')

@main.route('/privacy')
def privacy():
    return render_template('privacy.html')

app/posts/routes.py
from datetime import datetime
from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app
from flask_login import current_user, login_required
from app.models import Posts
from app import db, Config
from app.posts.forms import JobPostForm, DeleteJobForm
from config import Config
import stripe
import os
from urllib.parse import urlparse
from hashids import Hashids

hashids = Hashids(min_length=5, salt=Config.SECRET_KEY)

stripe_keys = {
    'secret_key': Config.STRIPE_SECRET_KEY,
    'publishable_key': Config.STRIPE_PUBLISHABLE_KEY
}

stripe.api_key = stripe_keys['secret_key']


posts = Blueprint('posts', __name__)

@posts.route('/post_job', methods=['GET','POST'])
def post_job():
    form = JobPostForm()
    if form.validate_on_submit():
        title = form.title.data
        poster_email = form.poster_email.data
        body = form.body.data
        apply_here_email = form.apply_here_email.data
        job_location = form.job_location.data
        org_name = form.org_name.data
        link_to_application_site = form.link_to_application_site.data
        # a datetime object -- DB has a Date object. Will only accept
        # python datetime objects
        date_posted = datetime.today()

        if current_user.is_authenticated:
            _paid = True
        else:
            _paid = False
        post_to_db = Posts(title=title, poster_email=poster_email, body=body,
                           apply_here_email=apply_here_email,
                           job_location=job_location,
                           date_posted=date_posted,
                           link_to_application_site=link_to_application_site,
                           org_name=org_name,
                           paid=_paid)
        db.session.add(post_to_db)
        db.session.commit()

        if current_user.is_authenticated:
            return redirect(url_for('main.home'))

        else:
            # flash('Thank you, your job posting has been submitted!', 'success')
            hashed_post_id = hashids.encode(post_to_db.id)
            return redirect(url_for('posts.pay', post_id=hashed_post_id))

    return render_template('post_job.html', title='Post a job', form=form,
                          charge_amount_usd=Config.CHARGE_AMOUNT_USD)

# TODO: Add a route that allows me to post for free so that I don't have to switch between the free version and real version live on the site

@posts.route('/edit_job/<post_id>', methods=['GET', 'POST'])
@login_required
def edit_job(post_id):
    hashed_post_id = post_id
    post_id = hashids.decode(post_id)
    form = JobPostForm()
    if form.validate_on_submit():
        print('Valid on submission')
        # get the existing post
        job_post = Posts.query.get_or_404(post_id)

        # get the data from the form
        job_post.title = form.title.data
        job_post.poster_email = form.poster_email.data
        job_post.body = form.body.data
        job_post.apply_here_email = form.apply_here_email.data
        job_post.job_location = form.job_location.data
        job_post.org_name = form.org_name.data
        job_post.link_to_application_site = form.link_to_application_site.data

        db.session.commit()
        flash('The job post has been updated!', 'success')
        return redirect(url_for('posts.view_job', post_id=hashed_post_id))

    elif request.method == 'GET':
        print('Getting form...')
        # prepopulate the form
        job_post = Posts.query.get_or_404(post_id)

        form.body.data = job_post.body
        form.title.data = job_post.title
        form.poster_email.data = job_post.poster_email
        form.apply_here_email.data = job_post.apply_here_email
        form.job_location.data = job_post.job_location
        form.org_name.data = job_post.org_name
        form.link_to_application_site.data = job_post.link_to_application_site

    return render_template('post_job.html', title='Edit job posting', form=form,
                           charge_amount_usd=Config.CHARGE_AMOUNT_USD)


@posts.route('/view_job/<post_id>', methods=['GET', 'POST'])
def view_job(post_id):
    hashed_post_id = post_id
    post_id = hashids.decode(post_id)
    job_post = Posts.query.get_or_404(post_id)
    return render_template('view_job.html', job_post=job_post)

@posts.route('/delete_job/<post_id>', methods=['GET','POST'])
@login_required
def delete_job(post_id):
    hashed_post_id = post_id
    post_id = hashids.decode(post_id)
    form = DeleteJobForm()
    job_post = Posts.query.get_or_404(post_id)
    if form.validate_on_submit():
        Posts.query.filter_by(id=post_id).delete()
        db.session.commit()
        flash('Post deleted', 'success')
        return redirect(url_for('main.home'))


    return render_template('delete_job.html', job_post=job_post, form=form)

@posts.route('/pay/<post_id>')
def pay(post_id):
    hashed_post_id = post_id
    post_id = hashids.decode(post_id)
    job_post = Posts.query.get_or_404(post_id)
    if not job_post.paid:
        charge_amount_dollars = Config.CHARGE_AMOUNT_USD
        charge_amount_cents = charge_amount_dollars*100
        return render_template('pay.html', key=stripe_keys['publishable_key'],
                            amount_usd=charge_amount_dollars,
                            amount_cents=charge_amount_cents,
                            post_id=hashed_post_id)
    else:
        flash('This job post is already paid for!', 'success')
        return redirect(url_for('main.home'))


@posts.route('/charge/<post_id>', methods=['POST'])
def charge(post_id):
    hashed_post_id = post_id
    post_id = hashids.decode(post_id)
    print(post_id)
    try:
        # amount in cents
        amount = Config.CHARGE_AMOUNT_USD*100

        customer = stripe.Customer.create(
            email=request.form['stripeEmail'],
            source=request.form['stripeToken']
        )

        stripe.Charge.create(
            customer=customer.id,
            amount=amount,
            currency='usd',
            description='Chirole Job Post Charge',
            receipt_email=customer.email
        )

        job_post = Posts.query.get_or_404(post_id)
        job_post.paid = True
        db.session.commit()

        flash('Thank you, your job posting has been submitted!', 'success')
        return redirect(url_for('main.home'))
        # return render_template('charge.html', amount=amount)
    except stripe.error.StripeError:
        Posts.query.filter_by(id=post_id).delete()
        db.session.commit()
        return render_template('error.html')

app/templates/about.html
{% extends "layout.html" %}
{% block content %}
	<!-- <section class="inner-banner" style="backend:#242c36 url(https://via.placeholder.com/1920x600)no-repeat;">
		<div class="container">
			<div class="caption">
                <h2>Questions?</h2>
                <p>Please send an email to: support@chirole.com</p>
			</div>
		</div>
	</section>
		<div class="container">
			<p>chirole is a specialized job board for roles that are at the intersection of chemistry, software development, data science, and machine learning </p>
		</div> -->

<section class="profile-detail">
		<div class="container">
			<div class="col-md-12">
				<div class="row">
					<div class="basic-information">
						<!-- <div class="col-md-3 col-sm-3"> -->
						 <!-- <img src="img/microsoft.png" alt="" class="img-responsive">
						</div> -->
						<div class="col-md-12 col-sm-9">
							<div class="profile-content">
								<h4>About this site</h4>
								<p>Chirole is a job board focused on jobs that are at the intersection of chemistry, software development, data science, and machine learning.</p>

								<h4>Looking for a challenging job where you can tackle problems in drug discovery, materials science, and other chemistry related fields?</h4>
								<p>For job seekers who want to leverage their machine learning, data science, and software engineering skills to solve tough chemistry problems, you can easily find and apply to those types of jobs here.</p>

								<h4>Need to fill an open position?</h4>
								<p>Other job boards are too unspecific, and your job posts get drowned out making it hard for qualified candidates to find.</p>
								<p>Posting here targets directly the candidates who have the skillset you are searching for and who want to apply software development, machine learning, and data science on tough chemistry problems.</p>
								<h4>Contact us</h4>
								<p>support@chirole.com</p>
								<p>Follow us on Twitter <a href="https://twitter.com/chirole2" target="_blank" class="fa fa-twitter"></a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

app/templates/delete_job.html
{% extends "layout.html" %} {% block content %}
<section class="profile-detail">
  <div class="container">
    <div class="col-md-12">
      <div class="row">
        <div class="basic-information">
          <!-- <div class="col-md-3 col-sm-3"> -->
          <!-- <img src="img/microsoft.png" alt="" class="img-responsive">
						</div> -->
          <div class="col-md-9 col-sm-9">
            <div class="profile-content">
              <h1>{{ job_post.title }}</h1>
              <p>{{ job_post.body }}</p>
              {% if job_post.apply_here_email %}
                <p>Inquire here: {{ job_post.apply_here_email }}</p>
              {% endif %}
              {% if job_post.link_to_application_site %}
                <a href="{{ 'http://'+job_post.link_to_application_site }}">Apply here: {{ job_post.link_to_application_site }}</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <form method="POST" action="">
        <!-- hidden_tag() adds a csf token to protect from certain attacks -->
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.accept.label(class="form-group-label") }} {% if
          form.accept.errors %} {{ form.accept(class="form-group form-group-lg
          is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.accept.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.accept(class="form-control") }} {% endif %}
        </div>
        <div class="form-group">
          {{ form.delete(class="btn btn-primary") }}
        </div>
      </form>
    </div>
  </div>
</section>

{% endblock content %}

app/templates/home.html
{% extends "layout.html" %}
{% block content %}
		<section class="jobs">
		<div class="container">
			<div class="row heading">
				<h2>Chemistry + Machine learning / Data Science / Software Engineering Jobs</h2>
				<!-- <h2>Find jobs that tackle <strong>chemistry</strong> problems with <strong>programming</strong>,
					<strong>data science</strong>, and <strong>machine learning</strong></h2> -->
				<!-- </br>
				<p>Chirole is focused on machine learning, data science, and programming jobs that tackle tough problems in drug discovery, materials science, and other tough problems in chemistry</p>
			</br> -->
				<p>You can follow us on Twitter <a href="https://twitter.com/chirole2" target="_blank" class="fa fa-twitter"></a></p>
			</br>

			</div>

			<div class="companies">
					{% for post in posts %}
						<div class="company-list">
						<div class="row">
							<!-- <div class="col-md-2 col-sm-2">
								<div class="company-logo">
									<img src="static/img/google.png" class="img-responsive" alt="" />
								</div>
							</div> -->
							<a href="{{ url_for('posts.view_job', post_id=(post.hashed_post_id)) }}">
							<div class="col-md-10 col-sm-8">
								<div class="company-content">
									<h3>{{ post.title }}</h3>
									<p><span class="company-name"><i class="fa fa-briefcase"></i>{{ post.org_name }}</span><span class="company-location"><i class="fa fa-map-marker"></i>{{ post.job_location }}</span><span class="package"><i class="fa fa-calendar"></i>{{'Posted: '}}{{ post.days_since_post }}</span></p>
								</div>
							</div></a>
						</div>
						</div>
										<!-- <a class="mr-2" href="{{ url_for('posts.view_job', post_id=post.id) }}">{{ 'Posted: ', post.days_since_post, post.date_str, post.title, post.org_name, post.job_location }}</a></br> -->
					{% endfor %}
			</div>
		</div>
{% endblock content %}

app/templates/layout.html
<!doctype html>
<html class="no-js" lang="en">
    <head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-164059648-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-164059648-1');
</script>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Chirole: Jobs that use chemistry, programming, data science, and machine learning</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

		<link href="{{url_for('static', filename='plugins.css')}}" rel="stylesheet">
		<link href="{{url_for('static', filename='common.css')}}" rel="stylesheet">
		<link href="{{url_for('static', filename='main.css')}}" rel="stylesheet">

    </head>

	<body>

		<!-- Navigation Start  -->
		<nav class="navbar navbar-default navbar-sticky bootsnav">

			<div class="container">
				<!-- Start Header Navigation -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
						<i class="fa fa-bars"></i>
					</button>
					<a class="navbar-brand" href="{{ url_for('main.home') }}"><h2>Chirole</h2></a>
				</div>
				<!-- End Header Navigation -->

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="navbar-menu">
					<ul class="nav navbar-nav navbar-right" data-in="fadeInDown" data-out="fadeOutUp">
							<li><a href="{{ url_for('main.home') }}">Home</a></li>
							<li><a href="{{ url_for('posts.post_job') }}">Post a job</a></li>
							<li><a href="{{ url_for('main.about') }}">About</a></li>
						</ul>
				</div><!-- /.navbar-collapse -->
			</div>
		</nav>
		<!-- Navigation End  -->
        <div class="container">
			<div class="row">
				{% with messages = get_flashed_messages(with_categories=true) %}
					{% if messages %}
						{% for category, message in messages %}
							<div class="alert alert-block alert-{{ category }}">
								{{ message }}
							</div>
						{% endfor %}
					{% endif %}
				{% endwith %}
				</div>
			</div>
		</div>
		{% block content %}{% endblock %}
        </body>
		<script type="text/javascript" src="static/js/jquery.min.js"></script>
		<script src="static/js/bootstrap.min.js"></script>
		<!-- <script type="text/javascript" src="js/owl.carousel.min.js"></script> -->
		<script src="static/js/main.js"></script>
		<script src="static/js/bootsnav.js"></script>
</html>

app/templates/logged_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chirole</title>
</head>
<body>
    <h1>You're logged in.</h1>


    {% for post in posts %}
    <a href="{{ url_for('posts.view_job', post_id=post.hashed_post_id) }}">
            <h3>{{ post.title, post.hashed_post_id, post.poster_email }}</h3>
            <p><span class="company-name"><i class="fa fa-briefcase"></i>{{ post.org_name }}</span><span class="company-location"><i class="fa fa-map-marker"></i>{{ post.job_location }}</span><span class="package"><i class="fa fa-calendar"></i>{{'Posted: '}}{{ post.days_since_post }}</span></p>
    {% endfor %}
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" action="">
        <!-- hidden_tag adds a csf token to protect from certain attacks -->
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log in</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</body>
</html>

app/templates/pay.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
<div class="col-md-8 col-sm-8">
    <h2>One last step to finalize!</h2>
    <p>Payment is handled by <a href="http://www.stripe.com">Stripe</a> and upon successful payment, your job post
    will be displayed for 30 days on the home page.</p>
    <p>Thank you!</p>
    <h4>${{ amount_usd }} to post job for 30 days</h4>
    <form action="/charge/{{ post_id }}" method="post">
      <script
        src="https://checkout.stripe.com/checkout.js"
        class="stripe-button"
        data-key="{{ key }}"
        data-description="Chirole Job Post Charge"
        data-amount="{{ amount_cents }}"
        data-locale="auto"
      ></script>
    </form>
  </div>
</div>
{% endblock content %}

app/templates/post_job.html
    {% extends "layout.html" %}
    {% block content %}
    <section class="profile-detail">
            <div class="container">
                <div class="col-md-12">
                    <div class="row">
                        <div class="basic-information">
                            <!-- <div class="col-md-3 col-sm-3"> -->
                            <!-- <img src="img/microsoft.png" alt="" class="img-responsive">
                            </div> -->
                            <div class="col-md-12 col-sm-9">
                                <div class="profile-content">
                                    <h2>Hire qualified chemists who know machine learning, data science, and software engineering</h2>
                                </br>
                                    <h4>Focused on chemistry jobs that require data science, machine learning, and programming</h4>
                                    <p>Other sites are too general and drown out your chemistry specific posting, which makes it harder for qualified candidates to find your open position.</p>
                                    <p>Speak directly to the exact candidates you are looking for; those who know how to apply software development, machine learning, and data science to chemistry problems.</p>
                                    <h4>Posting is fast and easy, applying is fast and easy</h4>
                                    <p>One form, one payment to post your job. Candidates don't need to register here to apply to your jobs -- they are only one simple click away from sending in their application to you.</p>
                                    <p>Don't lose out on great candidates because a job board site puts up extra hurdles for them to apply to your job.</p>
                                    <h4>What you receive</h4>
                                    <p>Your job advertisement will be posted on our home page for 30 days, and we will share your job on Twitter. The cost is only ${{ charge_amount_usd }} USD.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    <section class="login-wrapper">
        <div class="container">
            <div>
                <form method="POST" action="">
                    <!-- hidden_tag() adds a csf token to protect from certain attacks -->
                    {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.title.label(class="form-group-label") }}
                            {% if form.title.errors %}
                                {{ form.title(class="form-group form-group-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.title.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.title(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.poster_email.label(class="form-group-label") }}
                            {% if form.poster_email.errors %}
                                {{ form.poster_email(class="form-group form-group-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.poster_email.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.poster_email(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.body.label(class="form-group-label") }}
                            {% if form.body.errors %}
                                {{ form.body(class="form-group form-group-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.body.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.body(class="form-group col-md-12 col-sm-8", rows="10", cols="120") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.apply_here_email.label(class="form-group-label") }}
                            {% if form.apply_here_email.errors %}
                                {{ form.apply_here_email(class="form-group form-group-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.apply_here_email.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.apply_here_email(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.link_to_application_site.label(class="form-group-label") }}
                            {% if form.link_to_application_site.errors %}
                                {{ form.link_to_application_site(class="form-group form-group-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.link_to_application_site.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.link_to_application_site(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.job_location.label(class="form-group-label") }}
                            {% if form.job_location.errors %}
                                {{ form.job_location(class="form-group form-group-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.job_location.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.job_location(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.org_name.label(class="form-group-label") }}
                            {% if form.org_name.errors %}
                                {{ form.org_name(class="form-group form-group-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.org_name.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.org_name(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
			    <p><a href={{ url_for('main.tos') }}>Terms of Service</a></p>
			    <p><a href={{ url_for('main.privacy') }}>Privacy Policy</a></p>
                            {{ form.accept.label(class="form-group-label") }}
                            {% if form.accept.errors %}
                                {{ form.accept(class="form-group form-group-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.accept.errors %}
                                    <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.accept(class="form-control") }}
                            {% endif %}
                        </div>
                        <p>* required fields</p>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>
                </form>
    </div>
    </div>
    </section>
    </section>
{% endblock content %}

app/templates/privacy.html
<h2>Privacy Policy</h2>
<p>Your privacy is important to us. It is www.chirole.com's policy to respect your privacy regarding any information we may collect from you across our website, <a href="https://www.chirole.com">https://www.chirole.com</a>, and other sites we own and operate.</p>
<p>We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.</p>
<p>We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use or modification.</p>
<p>We don’t share any personally identifying information publicly or with third-parties, except when required to by law.</p>
<p>Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.</p>
<p>You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.</p>
<p>Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.</p>
<p>This policy is effective as of 19 April 2020.</p>
<p><a href="https://getterms.io" title="Generate a free privacy policy">Privacy Policy created with GetTerms.</a></p>